#!/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | /usr/bin/php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    /usr/bin/php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

unset GIT_DIR
cd $OPENSHIFT_REPO_DIR/php
/usr/bin/php $OPENSHIFT_DATA_DIR/composer.phar install --no-dev --prefer-source

rm -f app/storage/cache/*
rm -f app/storage/views/*
/usr/bin/php $OPENSHIFT_REPO_DIR/php/artisan cache:clear
/usr/bin/php $OPENSHIFT_REPO_DIR/php/artisan migrate

chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/storage/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/storage/logs
chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/storage/meta
chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/storage/sessions
chmod -R 0777 $OPENSHIFT_REPO_DIR/php/app/storage/views
